# Generated by Django 4.2.4 on 2023-08-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WmsAbsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_show",
                    models.BooleanField(
                        default=False, help_text="可用于控制删除", verbose_name="是否显示"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "edit_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="修改时间"),
                ),
                ("number", models.CharField(max_length=20, verbose_name="编号")),
                ("name", models.CharField(max_length=60, verbose_name="名称")),
                (
                    "specs",
                    models.CharField(
                        blank=True, max_length=60, null=True, verbose_name="规格"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, max_length=60, null=True, verbose_name="型号"
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, max_length=60, null=True, verbose_name="厂商"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="计量单位"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=10, max_digits=20, verbose_name="安全库存"
                    ),
                ),
                (
                    "total_number",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="包含所有仓库库区货架的该类物料",
                        max_digits=20,
                        verbose_name="库存总数",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "物料",
                "verbose_name_plural": "物料",
            },
        ),
        migrations.CreateModel(
            name="WmsArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_show",
                    models.BooleanField(
                        default=False, help_text="可用于控制删除", verbose_name="是否显示"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "edit_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="修改时间"),
                ),
                ("number", models.CharField(max_length=20, verbose_name="编号")),
                ("name", models.CharField(max_length=60, verbose_name="名称")),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "库区",
                "verbose_name_plural": "库区",
            },
        ),
        migrations.CreateModel(
            name="WmsDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_show",
                    models.BooleanField(
                        default=False, help_text="可用于控制删除", verbose_name="是否显示"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "edit_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="修改时间"),
                ),
                (
                    "carrier",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="承运商Id"
                    ),
                ),
                (
                    "delivery_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="发货日期"),
                ),
                (
                    "tracking_no",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="快递单号"
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "发货记录",
                "verbose_name_plural": "发货记录",
            },
        ),
        migrations.CreateModel(
            name="WmsInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_show",
                    models.BooleanField(
                        default=False, help_text="可用于控制删除", verbose_name="是否显示"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "edit_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="修改时间"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=20, verbose_name="库存"
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "当前库存",
                "verbose_name_plural": "当前库存",
            },
        ),
        migrations.CreateModel(
            name="WmsInventoryCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_show",
                    models.BooleanField(
                        default=False, help_text="可用于控制删除", verbose_name="是否显示"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "edit_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="修改时间"),
                ),
                (
                    "is_checked",
                    models.BooleanField(blank=True, null=True, verbose_name="是否审核"),
                ),
                (
                    "check_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
                ),
                (
                    "check_note",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="审核备注"
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        default="",
                        help_text="系统自动生成",
                        max_length=64,
                        verbose_name="盘点单号",
                    ),
                ),
                (
                    "inventory_check_type",
                    models.IntegerField(
                        blank=True,
                        help_text="0：仓库盘点，1: 库区盘点，2：货架盘点, 3: 物料盘点",
                        null=True,
                        verbose_name="盘点类型",
                    ),
                ),
                (
                    "inventory_check_status",
                    models.IntegerField(
                        default="11", help_text="11：盘点中 22：已完成", verbose_name="盘点单状态"
                    ),
                ),
                (
                    "inventory_check_total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=20, verbose_name="总盈亏数"
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "盘库单",
                "verbose_name_plural": "盘库单",
            },
        ),
        migrations.CreateModel(
            name="WmsInventoryCheckDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_show",
                    models.BooleanField(
                        default=False, help_text="可用于控制删除", verbose_name="是否显示"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "edit_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="修改时间"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="账面库存",
                    ),
                ),
                (
                    "check_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="实际库存",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "盘库单详情",
                "verbose_name_plural": "盘库单详情",
            },
        ),
        migrations.CreateModel(
            name="WmsInventoryHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_show",
                    models.BooleanField(
                        default=False, help_text="可用于控制删除", verbose_name="是否显示"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "edit_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="修改时间"),
                ),
                (
                    "form_type",
                    models.IntegerField(
                        blank=True,
                        help_text=" -2： 取消出库，-1: 取消入库，1:入库, 2 出库, 3: 移库, 4: 手动调整, 5:过期丢弃, 6: 其他",
                        null=True,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "number_type",
                    models.CharField(
                        blank=True,
                        help_text="入库 +， 出库 -, 移库要一对",
                        max_length=8,
                        null=True,
                        verbose_name="盈亏",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="库存变化",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="当期余额",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "库存变动记录",
                "verbose_name_plural": "库存变动记录",
            },
        ),
        migrations.CreateModel(
            name="WmsInventoryMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_show",
                    models.BooleanField(
                        default=False, help_text="可用于控制删除", verbose_name="是否显示"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "edit_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="修改时间"),
                ),
                (
                    "is_checked",
                    models.BooleanField(blank=True, null=True, verbose_name="是否审核"),
                ),
                (
                    "check_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
                ),
                (
                    "check_note",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="审核备注"
                    ),
                ),
                (
                    "number",
                    models.CharField(default="", max_length=64, verbose_name="编号"),
                ),
                (
                    "status",
                    models.IntegerField(
                        default=0,
                        help_text="-2：取消移动， -1：审核拒绝，0: 移库审批中，1：待移动，2：部分移动，3：按计划移动",
                        verbose_name="状态",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "移库单",
                "verbose_name_plural": "移库单",
            },
        ),
        migrations.CreateModel(
            name="WmsInventoryMovementDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_show",
                    models.BooleanField(
                        default=False, help_text="可用于控制删除", verbose_name="是否显示"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "edit_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="修改时间"),
                ),
                (
                    "plan_quantity",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=20, verbose_name="计划数量"
                    ),
                ),
                (
                    "real_quantity",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=20, verbose_name="实际数量"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        default=0,
                        help_text="-2：取消移动， -1：审核拒绝，0: 移库审批中，1：待移动，2：部分移动，3：按计划移动",
                        verbose_name="状态",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "库存移动详情",
                "verbose_name_plural": "库存移动详情",
            },
        ),
        migrations.CreateModel(
            name="WmsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_show",
                    models.BooleanField(
                        default=False, help_text="可用于控制删除", verbose_name="是否显示"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "edit_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="修改时间"),
                ),
                (
                    "batch_number",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="批次号"
                    ),
                ),
                (
                    "produce_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="生产日期"),
                ),
                (
                    "expiry_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="有效期至"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "批次物料",
                "verbose_name_plural": "批次物料",
            },
        ),
        migrations.CreateModel(
            name="WmsItemType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_show",
                    models.BooleanField(
                        default=False, help_text="可用于控制删除", verbose_name="是否显示"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "edit_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="修改时间"),
                ),
                (
                    "type_name",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="物料类型名称"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="0",
                        help_text="0正常 1停用",
                        max_length=1,
                        verbose_name="类型状态",
                    ),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
            ],
            options={
                "verbose_name": "物料类型",
                "verbose_name_plural": "物料类型",
            },
        ),
        migrations.CreateModel(
            name="WmsRack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_show",
                    models.BooleanField(
                        default=False, help_text="可用于控制删除", verbose_name="是否显示"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "edit_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="修改时间"),
                ),
                ("number", models.CharField(max_length=20, verbose_name="编号")),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=60, null=True, verbose_name="名称"
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "货架",
                "verbose_name_plural": "货架",
            },
        ),
        migrations.CreateModel(
            name="WmsReceiptOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_show",
                    models.BooleanField(
                        default=False, help_text="可用于控制删除", verbose_name="是否显示"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "edit_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="修改时间"),
                ),
                (
                    "number",
                    models.CharField(default="", max_length=64, verbose_name="入库单号"),
                ),
                (
                    "receipt_type",
                    models.IntegerField(
                        blank=True,
                        help_text="0 采购, 1 调库, 2 其他入库",
                        null=True,
                        verbose_name="入库类型",
                    ),
                ),
                (
                    "order_no",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="订单号"
                    ),
                ),
                (
                    "payable_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="订单金额",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        default=1,
                        help_text="-2: 取消入库，1: 待入库, 2:部分入库，3:按计划入库",
                        verbose_name="入库状态",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "入库单",
                "verbose_name_plural": "入库单",
            },
        ),
        migrations.CreateModel(
            name="WmsReceiptOrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_show",
                    models.BooleanField(
                        default=False, help_text="可用于控制删除", verbose_name="是否显示"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "edit_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="修改时间"),
                ),
                (
                    "plan_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="计划数量",
                    ),
                ),
                (
                    "real_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="实际数量",
                    ),
                ),
                (
                    "money",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="金额",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        default=1,
                        help_text="-2: 取消入库，1: 待入库, 2:部分入库，3:按计划入库",
                        verbose_name="入库状态",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "入库单详情",
                "verbose_name_plural": "入库单详情",
            },
        ),
        migrations.CreateModel(
            name="WmsShipmentOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_show",
                    models.BooleanField(
                        default=False, help_text="可用于控制删除", verbose_name="是否显示"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "edit_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="修改时间"),
                ),
                (
                    "is_checked",
                    models.BooleanField(blank=True, null=True, verbose_name="是否审核"),
                ),
                (
                    "check_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
                ),
                (
                    "check_note",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="审核备注"
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        default="", max_length=64, verbose_name="出库单号，系统自动生成"
                    ),
                ),
                (
                    "shipment_order_type",
                    models.IntegerField(
                        default=1, help_text="1、物料申请单 2、出库单", verbose_name="出库类型"
                    ),
                ),
                (
                    "order_no",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="出库订单"
                    ),
                ),
                (
                    "to_customer",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="外部领用人"
                    ),
                ),
                (
                    "receivable_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="订单金额",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        default=0,
                        help_text="-2：取消出库，-1: 审批拒绝，0: 出库审批中, 1: 待出库, 2: 部分出库， 3: 按计划出库",
                        verbose_name="出库单状态",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "出库单",
                "verbose_name_plural": "出库单",
            },
        ),
        migrations.CreateModel(
            name="WmsShipmentOrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_show",
                    models.BooleanField(
                        default=False, help_text="可用于控制删除", verbose_name="是否显示"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "edit_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="修改时间"),
                ),
                (
                    "plan_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="计划数量",
                    ),
                ),
                (
                    "real_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="实际数量",
                    ),
                ),
                (
                    "money",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="金额",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        default=0,
                        help_text="-2：取消出库，-1: 审批拒绝，0: 出库审批中, 1: 待出库, 2: 部分出库， 3: 按计划出库",
                        verbose_name="出库状态",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "出库单详情",
                "verbose_name_plural": "出库单详情",
            },
        ),
        migrations.CreateModel(
            name="WmsSupplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_show",
                    models.BooleanField(
                        default=False, help_text="可用于控制删除", verbose_name="是否显示"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "edit_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="修改时间"),
                ),
                ("number", models.CharField(max_length=20, verbose_name="编号")),
                ("name", models.CharField(max_length=60, verbose_name="企业抬头")),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="开户行"
                    ),
                ),
                (
                    "bank_account",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="银行账户"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="地址"
                    ),
                ),
                (
                    "mobile_no",
                    models.CharField(
                        blank=True, max_length=13, null=True, verbose_name="手机号"
                    ),
                ),
                (
                    "tel_no",
                    models.CharField(
                        blank=True, max_length=13, null=True, verbose_name="座机号"
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="联系人"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="级别"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "供应商",
                "verbose_name_plural": "供应商",
            },
        ),
        migrations.CreateModel(
            name="WmsWarehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_show",
                    models.BooleanField(
                        default=False, help_text="可用于控制删除", verbose_name="是否显示"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "edit_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="修改时间"),
                ),
                ("number", models.CharField(max_length=20, verbose_name="编号")),
                ("name", models.CharField(max_length=50, verbose_name="名称")),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "仓库",
                "verbose_name_plural": "仓库",
            },
        ),
    ]
