from WMS.tests import test_WmsItemType
from WMS.tests import test_WmsAbsItem
from WMS.tests import test_WmsItem
from WMS.tests import test_WmsWarehouse
from WMS.tests import test_WmsArea
from WMS.tests import test_WmsRack
from WMS.tests import test_WmsReceiptOrder
from WMS.tests import test_WmsReceiptOrderDetail
from WMS.tests import test_WmsShipmentOrder
from WMS.tests import test_WmsShipmentOrderDetail
from WMS.tests import test_WmsDelivery
from WMS.tests import test_WmsInventory
from WMS.tests import test_WmsInventoryHistory
from WMS.tests import test_WmsInventoryMovement
from WMS.tests import test_WmsInventoryMovementDetail
from WMS.tests import test_WmsInventoryCheck
from WMS.tests import test_WmsInventoryCheckDetail
from WMS.tests import test_WmsSupplier
