# Generated by Django 4.2.4 on 2023-08-29 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tools.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommonFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_show",
                    models.BooleanField(
                        default=False, help_text="可用于控制删除", verbose_name="是否显示"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "edit_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="修改时间"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="名称"
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="uuid"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="文件类型"
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="uploads/common_files/2023/8",
                        validators=[tools.utils.validate_file_extension],
                        verbose_name="文件",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="edited_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="修改人",
                    ),
                ),
            ],
            options={
                "verbose_name": "其他文件",
                "verbose_name_plural": "其他文件",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserIcon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_show",
                    models.BooleanField(
                        default=False, help_text="可用于控制删除", verbose_name="是否显示"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "edit_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="修改时间"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="名称"
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="uuid"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="文件类型"
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="uploads/user_icon/2023/8",
                        validators=[tools.utils.validate_file_extension],
                        verbose_name="文件",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="edited_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="修改人",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户头像",
                "verbose_name_plural": "用户头像",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="openWMS", max_length=32, verbose_name="站点名称"
                    ),
                ),
                (
                    "short_site_name",
                    models.CharField(
                        blank=True,
                        default="WMS",
                        help_text="侧边栏收起的时候使用",
                        max_length=16,
                        null=True,
                        verbose_name="名称简写",
                    ),
                ),
                (
                    "copy_right_company_name",
                    models.CharField(
                        blank=True,
                        default="CC",
                        max_length=32,
                        null=True,
                        verbose_name="版权旁边公司名称",
                    ),
                ),
                (
                    "system_name",
                    models.CharField(
                        blank=True,
                        default="openWMS",
                        max_length=32,
                        null=True,
                        verbose_name="版本旁边系统名称",
                    ),
                ),
                (
                    "record",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="备案信息"
                    ),
                ),
                (
                    "record_link",
                    models.CharField(
                        blank=True,
                        default="https://beian.miit.gov.cn/#/Integrated/index",
                        max_length=128,
                        null=True,
                        verbose_name="备案信息",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        default="Bata v0.0.1",
                        max_length=32,
                        null=True,
                        verbose_name="站点版本",
                    ),
                ),
                (
                    "other_info",
                    models.CharField(
                        blank=True,
                        help_text="比如地址等信息，放在网站脚部",
                        max_length=32,
                        null=True,
                        verbose_name="其他信息",
                    ),
                ),
                (
                    "big_logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="big_logo_sysinfo",
                        to="utils.commonfile",
                        verbose_name="logo大图",
                    ),
                ),
                (
                    "other_icon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="other_icon",
                        to="utils.commonfile",
                        verbose_name="其他icon",
                    ),
                ),
                (
                    "small_logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="small_logo_sysinfo",
                        to="utils.commonfile",
                        verbose_name="logo缩略图",
                    ),
                ),
            ],
            options={
                "verbose_name": "系统信息",
                "verbose_name_plural": "系统信息",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="InventoryFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_show",
                    models.BooleanField(
                        default=False, help_text="可用于控制删除", verbose_name="是否显示"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "edit_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="修改时间"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="名称"
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="uuid"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="文件类型"
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="uploads/inventory_files/2023/8",
                        validators=[tools.utils.validate_file_extension],
                        verbose_name="盘库单附件",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="edited_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="修改人",
                    ),
                ),
            ],
            options={
                "verbose_name": "盘库单附件",
                "verbose_name_plural": "盘库单附件",
                "abstract": False,
            },
        ),
    ]
